---
- hosts: '{{ target }}'
  # remote_user: 
  gather_facts: true
  become_user: root
  become_method: sudo
  become: yes

  vars:

    ansible_testabc: "testabc_var"

  tasks: 

    - name: Touch the same file, but add/remove some permissions
      file:
        path: /etc/foo.conf
        state: touch
        mode: u+rw,g-wx,o-rwx